"""update subscribers table structure

Revision ID: 55b5b4277c49
Revises: 757054995ce6
Create Date: 2025-05-08 17:46:12.946399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b5b4277c49'
down_revision: Union[str, None] = '757054995ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.add_column('subscribers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('subscribers', sa.Column('subscription_type', sa.Integer(), nullable=False))
    op.add_column('subscribers', sa.Column('payment_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('subscribers', sa.Column('subscription_end', sa.DateTime(), nullable=False))
    op.add_column('subscribers', sa.Column('payment_id', sa.String(), nullable=True))
    op.drop_index('ix_subscribers_user_id', table_name='subscribers')
    op.create_index(op.f('ix_subscribers_telegram_id'), 'subscribers', ['telegram_id'], unique=True)
    op.drop_column('subscribers', 'invoice_id')
    op.drop_column('subscribers', 'joined_at')
    op.drop_column('subscribers', 'expires_at')
    op.drop_column('subscribers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('subscribers', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.add_column('subscribers', sa.Column('joined_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('subscribers', sa.Column('invoice_id', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_subscribers_telegram_id'), table_name='subscribers')
    op.create_index('ix_subscribers_user_id', 'subscribers', ['user_id'], unique=1)
    op.drop_column('subscribers', 'payment_id')
    op.drop_column('subscribers', 'subscription_end')
    op.drop_column('subscribers', 'payment_date')
    op.drop_column('subscribers', 'subscription_type')
    op.drop_column('subscribers', 'first_name')
    op.drop_column('subscribers', 'telegram_id')
    # ### end Alembic commands ###
