"""Make payment_date and subscription_end nullable

Revision ID: ce961a2f8e77
Revises: b7a10e4ca607
Create Date: 2025-05-11 18:34:21.462310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce961a2f8e77'
down_revision: Union[str, None] = 'b7a10e4ca607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'payment_date',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('subscribers', 'subscription_end',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'subscription_end',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('subscribers', 'payment_date',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###
